### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by crutchcorn** [d-fischer/rate-limiter#5]
I'm currently debugging an issue with `twitch` I'm having within OBS's built-in browser plugin (I'm still investigating. Not enough information to open an issue yet) that I believe has something to do with `rate-limiter`'s bump from `0.2.7` to `0.4.2` in the upstream package.

While I'm able to go through commit history to figure out the changes between these versions, it might be nice to have a CHANGELOG.md file or release tags for future releases of this package

**Comment by d-fischer** [comment]
Maybe, at some point, this package will get a bump to a properly supported package. Right now though, this is basically just a complementary package to the Twurple family, and thus doesn't get all the bells and whistles you might expect, due to time constraints (I still work pretty much alone on this whole complex of packages).
